### ISSUE TITLE
json like text is converted to json

### ISSUE THREAD

**Issue by 0x6e756c6c** [wvffle/emojicrypt.js#1]
If you encrypt and decrypt string '{}' it should return the same string but it returns an empty object

```js
const str = '{}'
emojicrypt.decrypt(emojicrypt.encrypt(str)) === str // false
```

**Comment by wvffle** [comment]
Adding one more emoji will make short messages too long ;/
I'm not sure if it is essential to preserve output as a string. Parsing to json could be a feature! xD
